<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>secret.test-v0.6</AssemblyName>
    <RootNamespace>SecretFix</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <VersionPrefix>0.6.0</VersionPrefix>
    <InformationalVersion>v0.6-test</InformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\Branding\secret-fix-logo.png" />
    <Resource Include="Assets\Devices\**\*.png" />
    <Content Include="Assets\Branding\secret-fix-logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Include="Assets\Devices\**\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Include="Assets\Backgrounds\red-galaxy.mp4">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>
</Project>
